### PR TITLE
Liquid

### PR DESCRIPTION
**Pull request by futuri**

### CODE REVIEW

**Comment by entozoon** [comment]
@futuri Seems a little shady. Please contribute to this project rather than copying it

**Comment by entozoon** [comment]
Can't imagine how that would work. The main feature of this project is uploading to Shopify. In fact it doesn't offer much else, so for any other purposes I wouldn't recommend it but good luck I guess?

**Comment by futuri** [comment]
You are right. I should have specified a Shopify clone.

**Comment by futuri** [comment]
It is a small personal project that I do during my free time, I sent you an email

**Comment by entozoon** [comment]
Very interesting! It would be a cool concept to expand Slatest to work with other store APIs such as yours

**Pull request closed without merging**
